name: ci
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: sudo apt update -yqq && sudo apt install -yqq ninja-build clang-18
      - name: configure gcc
        run: cmake -S . --preset=default -B build -DCMAKE_CXX_COMPILER=g++-13
      - name: build gcc
        run: cmake --build build --config=Release
      - name: Run GCC Program and Save Output
        run: |
          ./build/Release/LinearAlgebraExample

      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: gcc_output.txt
          path: gcc_output.txt

      
      - name: configure clang
        run: cmake -S . --preset=ninja-clang -B clang -DCMAKE_CXX_COMPILER=clang++-18
      - name: build clang
        run: cmake --build clang --config=Release
      - name: Run clang Program and Save Output
        run: |
          ./clang/Release/LinearAlgebraExample

      - name: Upload Clang Output
        uses: actions/upload-artifact@v4
        with:
          name: clang_output.txt
          path: clang_output.txt
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake -S . --preset=vs22 -B build
      - name: build
        run: cmake --build build --config=Release

      - name: Run msvc Program and Save Output
        run: |
          ./build/Release/LinearAlgebraExample.exe

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: msvc_output.txt
          path: msvc_output.txt

  compare-results:
    name: Compare Outputs
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Output
        uses: actions/download-artifact@v4
        with:
          name: msvc_output.txt

      - name: Download Linux Output
        uses: actions/download-artifact@v4
        with:
          name: gcc_output.txt


      - name: Compare Outputs
        run: |
          diff -u gcc_output.txt msvc_output.txt || (echo "Mismatch detected between gcc and msvc!" && exit 1)
      
          
      - name: Download Linux Output
        uses: actions/download-artifact@v4
        with:
          name: clang_output.txt
      
      
      - name: Compare Outputs
        run: |
          diff -u clang_output.txt msvc_output.txt || (echo "Mismatch detected between clang and msvc!" && exit 1)
      
      
      - name: Compare Outputs
        run: |
          diff -u clang_output.txt gcc_output.txt || (echo "Mismatch detected between clang and gcc!" && exit 1)